blank_issues_enabled: false
contact_links:
  - name: User Forum
    url: https://forum.flowee-bpms.io/
    about: Ask questions about using Flowee BPMS Platform here.
  - name: Enterprise Support
    url: https://docs.flowee-bpms.org/enterprise/support/
    about: As an enterprise customer, contact our product support here.